import type { ReactNode } from 'react';

export type DialogVariant =
  /** Standard look and feel with primary brand colors */
  | 'default'
  /** Error/Critical state with red accents for destructive actions */
  | 'destructive'
  /** Positive state with green accents for successful operations */
  | 'success'
  /** Caution state with amber accents to warn the user */
  | 'warning'
  /** Informational state with blue accents for helpful tips */
  | 'info';

export type DialogPreset =
  /** No preset buttons, use children or the footer prop to provide your own */
  | 'custom'
  /** Single "OK" button for simple notices */
  | 'alert'
  /** "Cancel" and "Confirm" buttons for choices requiring verification */
  | 'confirm';

export type DialogAnimation =
  /** Smooth opacity transition without movement */
  | 'fade'
  /** Default spring-based scale up effect from the center */
  | 'scale'
  /** Enters by sliding up from the bottom boundary */
  | 'slideUp'
  /** Enters by sliding down from the top boundary */
  | 'slideDown'
  /** Enters by sliding in from the right side of the screen */
  | 'slideLeft'
  /** Enters by sliding in from the left side of the screen */
  | 'slideRight'
  /** High-energy entrance with overshoot and bounce back */
  | 'elastic'
  /** Gravity-style bounce dropping from the top */
  | 'bounce'
  /** Modern 3D perspective flip along the X-axis */
  | 'flip'
  /** Cinematic entrance featuring rotation and scaling */
  | 'zoom';

export interface DialogProps {
  /** Controls if the dialog is visible. Controlled component state. */
  open: boolean;
  /** Emitted when the user attempts to close the dialog (via overlay, ESC, or close button). */
  onOpenChange?: (open: boolean) => void;
  /** Bold heading displayed at the top of the dialog. */
  title?: string;
  /** Subtext displayed below the title, perfect for explaining the action. */
  description?: ReactNode;
  /** Primary content of the dialog. Use this for forms, lists, or custom layouts. */
  children?: ReactNode;
  /** Custom footer element. Overrides the buttons generated by 'preset'. */
  footer?: ReactNode;
  /** If enabled, clicking the dimmed background will trigger onOpenChange(false). Defaults to true. */
  closeOnOverlay?: boolean;
  /** Displays a small 'X' button in the top right corner. Defaults to true. */
  showClose?: boolean;
  /** Custom CSS classes to apply to the dialog container (e.g. padding, background overrides). */
  className?: string;
  /** Utility class for controlling responsive width (e.g. 'max-w-md', 'max-w-4xl'). */
  widthClassName?: string;
  /**
   * Color theme of the dialog. Affects icon color and button styles.
   * Options: 'default', 'destructive', 'success', 'warning', 'info'
   */
  variant?: DialogVariant;
  /**
   * Quick-start configurations for buttons. Use 'custom' to hide all default buttons.
   * Options: 'custom', 'alert', 'confirm'
   */
  preset?: DialogPreset;
  /** Text shown on the primary action button. Defaults to "OK". */
  confirmLabel?: string;
  /** Text shown on the secondary/cancel button. Defaults to "Cancel". */
  cancelLabel?: string;
  /** Triggered when the primary action button is clicked. */
  onConfirm?: () => void;
  /** Triggered when the secondary/cancel button is clicked. */
  onCancel?: () => void;
  /** Displays a loading spinner on the confirm button and disables interactions. */
  loading?: boolean;
  /** Optional icon to display next to the title. Overrides the default variant icon. */
  icon?: ReactNode;
  /**
   * Visual entrance and exit effect for the dialog box. Defaults to 'scale'.
   * Options: 'fade', 'scale', 'slideUp', 'slideDown', 'slideLeft', 'slideRight', 'elastic', 'bounce', 'flip', 'zoom'
   */
  animation?: DialogAnimation;
}
