// Highlighted sidebar items
export const NEW: string[] = [
  'Liquid Ether',
  'Shuffle',
  'Laser Flow',
  'Ghost Cursor',
  'Color Bends',
  'Grid Scan',
  'Floating Lines',
  'Light Pillar',
  'Antigravity',
  'Reflective Card'
];

export const UPDATED: string[] = ['Profile Card', 'Logo Loop', 'Animated Content', 'Fade Content', 'Stack'];

// Category type definition
export interface Category {
  name: string;
  subcategories: string[];
}

// Used for main sidebar navigation
export const CATEGORIES: Category[] = [
  {
    name: 'Get Started',
    subcategories: ['Introduction', 'Installation', 'MCP', 'Index']
  },
  /*
  {
    name: 'Text Animations',
    subcategories: [
      'Split Text',
      'Blur Text',
      'Circular Text',
      'Text Type',
      'Shuffle',
      'Shiny Text',
      'Text Pressure',
      'Curved Loop',
      'Fuzzy Text',
      'Gradient Text',
      'Falling Text',
      'Text Cursor',
      'Decrypted Text',
      'True Focus',
      'Scroll Float',
      'Scroll Reveal',
      'ASCII Text',
      'Scrambled Text',
      'Rotating Text',
      'Glitch Text',
      'Scroll Velocity',
      'Variable Proximity',
      'Count Up',
      'Search'
    ]
  },
  {
    name: 'Animations',
    subcategories: [
      'Animated Content',
      'Fade Content',
      'Electric Border',
      'Pixel Transition',
      'Glare Hover',
      'Antigravity',
      'Logo Loop',
      'Target Cursor',
      'Laser Flow',
      'Magnet Lines',
      'Ghost Cursor',
      'Gradual Blur',
      'Click Spark',
      'Magnet',
      'Sticker Peel',
      'Pixel Trail',
      'Cubes',
      'Metallic Paint',
      'Noise',
      'Shape Blur',
      'Crosshair',
      'Image Trail',
      'Ribbons',
      'Splash Cursor',
      'Meta Balls',
      'Blob Cursor',
      'Star Border',
      'Search'
    ]
  },
  {
    name: 'Components',
    subcategories: [
      'Animated List',
      'Scroll Stack',
      'Bubble Menu',
      'Magic Bento',
      'Circular Gallery',
      'Reflective Card',
      'Card Nav',
      'Stack',
      'Fluid Glass',
      'Pill Nav',
      'Tilted Card',
      'Masonry',
      'Glass Surface',
      'Dome Gallery',
      'Chroma Grid',
      'Folder',
      'Staggered Menu',
      'Model Viewer',
      'Lanyard',
      'Profile Card',
      'Dock',
      'Gooey Nav',
      'Pixel Card',
      'Carousel',
      'Spotlight Card',
      'Flying Posters',
      'Card Swap',
      'Glass Icons',
      'Decay Card',
      'Flowing Menu',
      'Elastic Slider',
      'Counter',
      'Infinite Menu',
      'Stepper',
      'Bounce Cards',
      'Search'
    ]
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Liquid Ether',
      'Prism',
      'Dark Veil',
      'Light Pillar',
      'Silk',
      'Floating Lines',
      'Light Rays',
      'Pixel Blast',
      'Color Bends',
      'Aurora',
      'Plasma',
      'Particles',
      'Gradient Blinds',
      'Grid Scan',
      'Beams',
      'Lightning',
      'Prismatic Burst',
      'Galaxy',
      'Dither',
      'Faulty Terminal',
      'Ripple Grid',
      'Dot Grid',
      'Threads',
      'Hyperspeed',
      'Iridescence',
      'Waves',
      'Grid Distortion',
      'Ballpit',
      'Orb',
      'Letter Glitch',
      'Grid Motion',
      'Squares',
      'Liquid Chrome',
      'Balatro',
      'Search'
    ]
  },
  */
  {
    name: 'UI Basics',
    subcategories: [
      'Combobox',
      'Button',
      'Input',
      'Checkbox',
      'Radio',
      'Switch',
      'Select',
      'Textarea',
      'Label',
      'Dialog',
      'Drawer',
      'Alert',
      'Toast',
      'Tooltip',
      'Accordion',
      'Card',
      'Stepper',
      'Chip',
      'Calendar',
      'DatePicker',
      'MultiSelect Combobox',
      'Hover Card',
      'Spotlight Card',
      'Splash Cursor',
      'Chroma Grid',
      'Color Palette',
      'Gradual Blur',
      'Animated Content',
      'Background Gradient',
      'Hover Border Gradient',
      'Button Hover Border Gradient',
      'Password Strength Meter',
      'Sun To Moon Button',
      'Carousel',
      'Preview',
      'OTPInput',
      'Form',
      'Data Table',
      'Loading',
      'Skeleton',
      'Area Chart',
      'Bar Chart',
      'Pie Chart',
      'Neon Line Chart',
      'Stacked Bar Chart',
      'Thin Breakdown Bar',
      'Icons',
      'Typography',
      'Search'
    ]
  }
];
